# Generated by Django 6.0.1 on 2026-02-23 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_placehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateCreditApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(max_length=120)),
                ('id_type', models.CharField(choices=[('aadhaar', 'Aadhaar'), ('pan', 'PAN')], max_length=20)),
                ('borrower_id', models.CharField(max_length=20)),
                ('location_state', models.CharField(default='India', max_length=80)),
                ('location_district', models.CharField(max_length=80)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('income', models.FloatField()),
                ('base_credit_score', models.PositiveIntegerField()),
                ('loan_amount', models.FloatField()),
                ('is_location_valid', models.BooleanField(default=False)),
                ('rainfall_trend', models.FloatField(default=0)),
                ('flood_history', models.FloatField(default=0)),
                ('cyclone_path_risk', models.FloatField(default=0)),
                ('drought_index', models.FloatField(default=0)),
                ('climate_risk_score', models.PositiveIntegerField(default=0)),
                ('climate_risk_classification', models.CharField(default='Low', max_length=16)),
                ('adjusted_credit_score', models.PositiveIntegerField(default=0)),
                ('suggested_interest_rate', models.FloatField(default=0)),
                ('suggested_collateral_ratio', models.FloatField(default=0)),
                ('suggested_tenure_months', models.PositiveIntegerField(default=0)),
                ('decision', models.CharField(choices=[('Auto Approve', 'Auto Approve'), ('Conditional Approve', 'Conditional Approve'), ('Reject', 'Reject')], default='Conditional Approve', max_length=30)),
                ('esg_risk_score', models.PositiveIntegerField(default=0)),
                ('default_probability', models.FloatField(default=0)),
                ('manager_override_decision', models.CharField(blank=True, choices=[('Auto Approve', 'Auto Approve'), ('Conditional Approve', 'Conditional Approve'), ('Reject', 'Reject')], max_length=30)),
                ('final_decision', models.CharField(choices=[('Auto Approve', 'Auto Approve'), ('Conditional Approve', 'Conditional Approve'), ('Reject', 'Reject')], default='Conditional Approve', max_length=30)),
                ('decision_rationale', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climate_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create Application'), ('override', 'Manager Override'), ('final_confirm', 'Final Decision Confirmation')], max_length=40)),
                ('decision', models.CharField(blank=True, max_length=30)),
                ('risk_factors', models.TextField(blank=True)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.climatecreditapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('officer', 'Officer'), ('manager', 'Manager'), ('auditor', 'Auditor')], default='officer', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='LoanApplication',
        ),
    ]
