# Generated by Django 6.0.1 on 2026-02-23 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_climatecreditapplication_auditlog_userprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='climatecreditapplication',
            name='model_algorithm',
            field=models.CharField(default='RandomForestRegressor', max_length=60),
        ),
        migrations.AddField(
            model_name='climatecreditapplication',
            name='model_confidence',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='LocationCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('rainfall_index', models.FloatField(default=50)),
                ('flood_index', models.FloatField(default=40)),
                ('cyclone_index', models.FloatField(default=30)),
                ('drought_index', models.FloatField(default=45)),
                ('is_custom', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
