# Generated by Django 6.0.1 on 2026-02-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_climatecreditapplication_model_algorithm_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationcatalog',
            options={'ordering': ['state', 'name']},
        ),
        migrations.AddField(
            model_name='climatecreditapplication',
            name='ai_credit_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='climatecreditapplication',
            name='early_warning_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='climatecreditapplication',
            name='early_warning_message',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='climatecreditapplication',
            name='esg_aligned_credit_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='climatecreditapplication',
            name='esg_lending_recommendation',
            field=models.CharField(default='Standard Monitoring', max_length=120),
        ),
        migrations.AddField(
            model_name='climatecreditapplication',
            name='property_risk_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='climatecreditapplication',
            name='property_type',
            field=models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Farm', 'Farm'), ('Commercial', 'Commercial')], default='House', max_length=20),
        ),
        migrations.AddField(
            model_name='climatecreditapplication',
            name='property_value',
            field=models.FloatField(default=0),
        ),
    ]
