# Generated by Django 6.0.1 on 2026-02-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_doctorpatient_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdocument',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='parsed_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
