# Generated by Django 6.0.1 on 2026-03-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_patientdocument_extracted_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='diagnosis',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='medications',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
