# Generated by Django 6.0.1 on 2026-03-15 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_appointmentrequest_preferred_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ai_diagnoses/')),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('disease_prediction', models.CharField(blank=True, max_length=200, null=True)),
                ('solution', models.TextField(blank=True, null=True)),
                ('recommended_specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_diagnoses', to='core.patientprofile')),
            ],
        ),
    ]
