# Generated by Django 6.0.1 on 2026-03-15 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_aidiagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidiagnosis',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visual_diagnoses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aidiagnosis',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_diagnoses', to='core.patientprofile'),
        ),
    ]
